import { Team } from '@/types/teams'
import { Player } from '@/types'

/**
 * Helper function to create the Mooninites team from the provided data
 */
export function createMooninitesTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'mooninites-celebini',
      name: 'Macklin Celebrini',
      position: 'C',
      team: 'SJ',
      rank: 3,
      startPercentage: 81,
      rosPercentage: 99,
      status: 'healthy',
      value: 75.0,
      stats: {
        goals: 14,
        hockeyAssists: 20,
        hockeyPoints: 34,
        plusMinus: 3,
        pim: 12,
        ppp: 12,
        shp: 0,
        gwg: 3,
        sog: 70,
        fw: 181,
        hit: 14,
        blk: 16,
      },
    },
    {
      id: 'mooninites-suzuki',
      name: 'Nick Suzuki',
      position: 'C',
      team: 'MTL',
      rank: 28,
      startPercentage: 71,
      rosPercentage: 99,
      status: 'healthy',
      value: 72.0,
      stats: {
        goals: 7,
        hockeyAssists: 19,
        hockeyPoints: 26,
        plusMinus: 12,
        pim: 4,
        ppp: 11,
        shp: 0,
        gwg: 0,
        sog: 46,
        fw: 201,
        hit: 18,
        blk: 22,
      },
    },
    {
      id: 'mooninites-panarin',
      name: 'Artemi Panarin',
      position: 'LW',
      team: 'NYR',
      rank: 136,
      startPercentage: 87,
      rosPercentage: 99,
      status: 'healthy',
      value: 85.0,
      stats: {
        goals: 7,
        hockeyAssists: 15,
        hockeyPoints: 22,
        plusMinus: -4,
        pim: 6,
        ppp: 6,
        shp: 0,
        gwg: 2,
        sog: 66,
        hit: 3,
        blk: 2,
      },
    },
    {
      id: 'mooninites-rantanen',
      name: 'Mikko Rantanen',
      position: 'LW,RW',
      team: 'DAL',
      rank: 8,
      startPercentage: 79,
      rosPercentage: 100,
      status: 'healthy',
      value: 95.0,
      stats: {
        goals: 10,
        hockeyAssists: 18,
        hockeyPoints: 28,
        plusMinus: -5,
        pim: 57,
        ppp: 15,
        shp: 0,
        gwg: 1,
        sog: 60,
        fw: 14,
        hit: 19,
        blk: 14,
      },
    },
    {
      id: 'mooninites-thompson',
      name: 'Tage Thompson',
      position: 'C,RW',
      team: 'BUF',
      rank: 82,
      startPercentage: 80,
      rosPercentage: 98,
      status: 'healthy',
      value: 68.5,
      stats: {
        goals: 12,
        hockeyAssists: 9,
        hockeyPoints: 21,
        plusMinus: -6,
        pim: 10,
        ppp: 5,
        shp: 0,
        gwg: 0,
        sog: 87,
        fw: 101,
        hit: 30,
        blk: 11,
      },
    },
    {
      id: 'mooninites-caufield',
      name: 'Cole Caufield',
      position: 'LW,RW',
      team: 'MTL',
      rank: 46,
      startPercentage: 77,
      rosPercentage: 99,
      status: 'healthy',
      value: 62.0,
      stats: {
        goals: 13,
        hockeyAssists: 10,
        hockeyPoints: 23,
        plusMinus: 10,
        pim: 8,
        ppp: 6,
        shp: 0,
        gwg: 3,
        sog: 62,
        fw: 2,
        hit: 20,
        blk: 6,
      },
    },
    // Defensemen
    {
      id: 'mooninites-fox',
      name: 'Adam Fox',
      position: 'D',
      team: 'NYR',
      rank: 48,
      startPercentage: 97,
      rosPercentage: 99,
      status: 'healthy',
      value: 85.0,
      stats: {
        goals: 3,
        hockeyAssists: 19,
        hockeyPoints: 22,
        plusMinus: 3,
        pim: 10,
        ppp: 6,
        shp: 1,
        gwg: 1,
        sog: 49,
        hit: 15,
        blk: 41,
      },
    },
    {
      id: 'mooninites-heiskanen',
      name: 'Miro Heiskanen',
      position: 'D',
      team: 'DAL',
      rank: 89,
      startPercentage: 95,
      rosPercentage: 97,
      status: 'healthy',
      value: 78.5,
      stats: {
        goals: 3,
        hockeyAssists: 17,
        hockeyPoints: 20,
        plusMinus: 1,
        pim: 6,
        ppp: 8,
        shp: 0,
        gwg: 1,
        sog: 54,
        hit: 4,
        blk: 40,
      },
    },
    {
      id: 'mooninites-hamilton',
      name: 'Dougie Hamilton',
      position: 'D',
      team: 'NJ',
      rank: 276,
      startPercentage: 80,
      rosPercentage: 89,
      status: 'healthy',
      value: 70.0,
      stats: {
        goals: 4,
        hockeyAssists: 4,
        hockeyPoints: 8,
        plusMinus: -1,
        pim: 14,
        ppp: 4,
        shp: 0,
        gwg: 1,
        sog: 48,
        hit: 19,
        blk: 23,
      },
    },
    // Bench/Util
    {
      id: 'mooninites-kane',
      name: 'Evander Kane',
      position: 'LW',
      team: 'VAN',
      rank: 148,
      startPercentage: 21,
      rosPercentage: 31,
      status: 'healthy',
      value: 25.0,
      stats: {
        goals: 4,
        hockeyAssists: 8,
        hockeyPoints: 12,
        plusMinus: -7,
        pim: 38,
        ppp: 4,
        shp: 0,
        gwg: 0,
        sog: 68,
        fw: 5,
        hit: 46,
        blk: 11,
      },
    },
    {
      id: 'mooninites-lundell',
      name: 'Anton Lundell',
      position: 'C',
      team: 'FLA',
      rank: 71,
      startPercentage: 31,
      rosPercentage: 39,
      status: 'healthy',
      value: 18.5,
      stats: {
        goals: 6,
        hockeyAssists: 12,
        hockeyPoints: 18,
        plusMinus: -5,
        pim: 10,
        ppp: 7,
        shp: 2,
        gwg: 0,
        sog: 46,
        fw: 222,
        hit: 24,
        blk: 17,
      },
    },
    {
      id: 'mooninites-marchenko',
      name: 'Kirill Marchenko',
      position: 'RW',
      team: 'CBJ',
      rank: 41,
      startPercentage: 39,
      rosPercentage: 94,
      status: 'DTD',
      value: 58.0,
      stats: {
        goals: 8,
        hockeyAssists: 14,
        hockeyPoints: 22,
        plusMinus: 8,
        pim: 8,
        ppp: 7,
        shp: 1,
        gwg: 2,
        sog: 65,
        hit: 19,
        blk: 15,
      },
    },
    {
      id: 'mooninites-hedman',
      name: 'Victor Hedman',
      position: 'D',
      team: 'TB',
      rank: 351,
      startPercentage: 27,
      rosPercentage: 96,
      status: 'IR-LT',
      value: 75.0,
      stats: {
        goals: 0,
        hockeyAssists: 12,
        hockeyPoints: 12,
        plusMinus: 1,
        pim: 4,
        ppp: 6,
        shp: 0,
        gwg: 0,
        sog: 23,
        hit: 7,
        blk: 28,
      },
    },
    // IR
    {
      id: 'mooninites-hughes',
      name: 'Jack Hughes',
      position: 'C,LW',
      team: 'NJ',
      rank: 117,
      startPercentage: 13,
      rosPercentage: 98,
      status: 'IR',
      value: 80.0,
      stats: {
        goals: 10,
        hockeyAssists: 10,
        hockeyPoints: 20,
        plusMinus: 3,
        pim: 0,
        ppp: 5,
        shp: 0,
        gwg: 2,
        sog: 69,
        fw: 52,
        hit: 2,
        blk: 10,
      },
    },
    // Goaltenders
    {
      id: 'mooninites-swayman',
      name: 'Jeremy Swayman',
      position: 'G',
      team: 'BOS',
      rank: 53,
      startPercentage: 70,
      rosPercentage: 90,
      status: 'healthy',
      value: 82.0,
      stats: {
        wins: 10,
        losses: 6,
        goalsAgainst: 43,
        saves: 463,
        shotsAgainst: 506,
        svp: 0.915,
        shutouts: 0,
      },
    },
    {
      id: 'mooninites-oettinger',
      name: 'Jake Oettinger',
      position: 'G',
      team: 'DAL',
      rank: 60,
      startPercentage: 79,
      rosPercentage: 100,
      status: 'healthy',
      value: 92.0,
      stats: {
        wins: 10,
        losses: 4,
        goalsAgainst: 44,
        saves: 398,
        shotsAgainst: 442,
        svp: 0.900,
        shutouts: 1,
      },
    },
    {
      id: 'mooninites-patera',
      name: 'Jiri Patera',
      position: 'G',
      team: 'VAN',
      rank: 481,
      startPercentage: 0,
      rosPercentage: 1,
      status: 'healthy',
      value: 5.0,
      stats: {
        wins: 0,
        losses: 1,
        goalsAgainst: 7,
        saves: 33,
        shotsAgainst: 40,
        svp: 0.825,
        shutouts: 0,
      },
    },
    {
      id: 'mooninites-hellebuyck',
      name: 'Connor Hellebuyck',
      position: 'G',
      team: 'WPG',
      rank: 80,
      startPercentage: 28,
      rosPercentage: 99,
      status: 'IR',
      value: 88.0,
      stats: {
        wins: 8,
        losses: 6,
        goalsAgainst: 35,
        saves: 369,
        shotsAgainst: 404,
        svp: 0.913,
        shutouts: 0,
      },
    },
  ]

  return {
    id: 'mooninites',
    name: 'Mooninites',
    owner: 'michael',
    record: '53-57-23',
    rank: 5,
    players,
  }
}

/**
 * Helper function to create The Brain Reigns team from Yahoo Sports data
 */
export function createBrainReignsTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'brain-reigns-stutzle',
      name: 'Tim Stutzle',
      position: 'C,LW',
      team: 'OTT',
      rank: 20,
      startPercentage: 88,
      rosPercentage: 99,
      status: 'healthy',
      value: 85.0,
      stats: {
        goals: 11,
        hockeyAssists: 12,
        hockeyPoints: 23,
        plusMinus: 8,
        pim: 8,
        ppp: 7,
        shp: 0,
        gwg: 3,
        sog: 59,
        fw: 129,
        hit: 41,
        blk: 17,
      },
    },
    {
      id: 'brain-reigns-cooley',
      name: 'Logan Cooley',
      position: 'C',
      team: 'UTA',
      rank: 43,
      startPercentage: 66,
      rosPercentage: 84,
      status: 'healthy',
      value: 70.0,
      stats: {
        goals: 13,
        hockeyAssists: 9,
        hockeyPoints: 22,
        plusMinus: 6,
        pim: 20,
        ppp: 4,
        shp: 1,
        gwg: 1,
        sog: 50,
        fw: 114,
        hit: 27,
        blk: 10,
      },
    },
    {
      id: 'brain-reigns-kaprizov',
      name: 'Kirill Kaprizov',
      position: 'LW',
      team: 'MIN',
      rank: 29,
      startPercentage: 86,
      rosPercentage: 100,
      status: 'healthy',
      value: 82.0,
      stats: {
        goals: 14,
        hockeyAssists: 14,
        hockeyPoints: 28,
        plusMinus: 1,
        pim: 6,
        ppp: 11,
        shp: 0,
        gwg: 2,
        sog: 80,
      },
    },
    {
      id: 'brain-reigns-draisaitl',
      name: 'Leon Draisaitl',
      position: 'C,LW',
      team: 'EDM',
      rank: 14,
      startPercentage: 34,
      rosPercentage: 100,
      status: 'healthy',
      value: 95.0,
      stats: {
        goals: 14,
        hockeyAssists: 15,
        hockeyPoints: 29,
        plusMinus: 4,
        pim: 6,
        ppp: 12,
        shp: 1,
        gwg: 1,
        sog: 61,
        fw: 227,
        hit: 14,
        blk: 8,
      },
    },
    {
      id: 'brain-reigns-robertson',
      name: 'Jason Robertson',
      position: 'LW,RW',
      team: 'DAL',
      rank: 13,
      startPercentage: 96,
      rosPercentage: 100,
      status: 'healthy',
      value: 92.0,
      stats: {
        goals: 14,
        hockeyAssists: 17,
        hockeyPoints: 31,
        plusMinus: 10,
        pim: 2,
        ppp: 14,
        shp: 0,
        gwg: 1,
        sog: 102,
        hit: 15,
        blk: 11,
      },
    },
    {
      id: 'brain-reigns-sherwood',
      name: 'Kiefer Sherwood',
      position: 'RW',
      team: 'VAN',
      rank: 57,
      startPercentage: 46,
      rosPercentage: 58,
      status: 'healthy',
      value: 55.0,
      stats: {
        goals: 12,
        hockeyAssists: 4,
        hockeyPoints: 16,
        plusMinus: -4,
        pim: 16,
        ppp: 5,
        shp: 1,
        gwg: 1,
        sog: 43,
        fw: 5,
        hit: 99,
        blk: 13,
      },
    },
    // Defensemen
    {
      id: 'brain-reigns-moser',
      name: 'J.J. Moser',
      position: 'D',
      team: 'TB',
      rank: 326,
      startPercentage: 1,
      rosPercentage: 2,
      status: 'healthy',
      value: 15.0,
      stats: {
        goals: 1,
        hockeyAssists: 6,
        hockeyPoints: 7,
        plusMinus: 11,
        pim: 12,
        ppp: 0,
        shp: 1,
        gwg: 0,
        sog: 25,
        hit: 17,
        blk: 27,
      },
    },
    {
      id: 'brain-reigns-sanderson',
      name: 'Jake Sanderson',
      position: 'D',
      team: 'OTT',
      rank: 130,
      startPercentage: 95,
      rosPercentage: 98,
      status: 'healthy',
      value: 75.0,
      stats: {
        goals: 4,
        hockeyAssists: 14,
        hockeyPoints: 18,
        plusMinus: 2,
        pim: 2,
        ppp: 8,
        shp: 0,
        gwg: 0,
        sog: 50,
        hit: 9,
        blk: 39,
      },
    },
    {
      id: 'brain-reigns-faber',
      name: 'Brock Faber',
      position: 'D',
      team: 'MIN',
      rank: 118,
      startPercentage: 66,
      rosPercentage: 75,
      status: 'healthy',
      value: 68.0,
      stats: {
        goals: 6,
        hockeyAssists: 9,
        hockeyPoints: 15,
        plusMinus: 1,
        pim: 2,
        ppp: 4,
        shp: 1,
        gwg: 1,
        sog: 56,
        hit: 10,
        blk: 44,
      },
    },
    {
      id: 'brain-reigns-thomas',
      name: 'Robert Thomas',
      position: 'C',
      team: 'STL',
      rank: 300,
      startPercentage: 56,
      rosPercentage: 78,
      status: 'healthy',
      value: 60.0,
      stats: {
        goals: 4,
        hockeyAssists: 10,
        hockeyPoints: 14,
        plusMinus: -2,
        pim: 4,
        ppp: 6,
        shp: 0,
        gwg: 0,
        sog: 29,
        fw: 180,
        hit: 3,
        blk: 11,
      },
    },
    // Bench
    {
      id: 'brain-reigns-byfield',
      name: 'Quinton Byfield',
      position: 'C,LW',
      team: 'LA',
      rank: 90,
      startPercentage: 16,
      rosPercentage: 79,
      status: 'healthy',
      value: 65.0,
      stats: {
        goals: 4,
        hockeyAssists: 13,
        hockeyPoints: 17,
        plusMinus: 0,
        pim: 10,
        ppp: 5,
        shp: 1,
        gwg: 2,
        sog: 59,
        fw: 133,
        hit: 19,
        blk: 7,
      },
    },
    {
      id: 'brain-reigns-kempe',
      name: 'Adrian Kempe',
      position: 'RW',
      team: 'LA',
      rank: 24,
      startPercentage: 31,
      rosPercentage: 98,
      status: 'healthy',
      value: 78.0,
      stats: {
        goals: 7,
        hockeyAssists: 13,
        hockeyPoints: 20,
        plusMinus: 3,
        pim: 16,
        ppp: 5,
        shp: 1,
        gwg: 3,
        sog: 76,
        fw: 12,
        hit: 46,
        blk: 14,
      },
    },
    // IR+
    {
      id: 'brain-reigns-mcavoy',
      name: 'Charlie McAvoy',
      position: 'D',
      team: 'BOS',
      rank: 179,
      startPercentage: 19,
      rosPercentage: 81,
      status: 'IR',
      value: 72.0,
      stats: {
        goals: 0,
        hockeyAssists: 14,
        hockeyPoints: 14,
        plusMinus: -2,
        pim: 26,
        ppp: 5,
        shp: 0,
        gwg: 0,
        sog: 25,
        hit: 26,
        blk: 32,
      },
    },
    // Goaltenders
    {
      id: 'brain-reigns-allen',
      name: 'Jake Allen',
      position: 'G',
      team: 'NJ',
      rank: 102,
      startPercentage: 18,
      rosPercentage: 31,
      status: 'healthy',
      value: 50.0,
      stats: {
        wins: 7,
        losses: 4,
        goalsAgainst: 29,
        saves: 287,
        shotsAgainst: 316,
        svp: 0.908,
        shutouts: 0,
      },
    },
    {
      id: 'brain-reigns-gustavsson',
      name: 'Filip Gustavsson',
      position: 'G',
      team: 'MIN',
      rank: 76,
      startPercentage: 81,
      rosPercentage: 97,
      status: 'healthy',
      value: 75.0,
      stats: {
        wins: 7,
        losses: 7,
        goalsAgainst: 45,
        saves: 420,
        shotsAgainst: 465,
        svp: 0.903,
        shutouts: 2,
      },
    },
    {
      id: 'brain-reigns-saros',
      name: 'Juuse Saros',
      position: 'G',
      team: 'NSH',
      rank: 241,
      startPercentage: 61,
      rosPercentage: 80,
      status: 'healthy',
      value: 65.0,
      stats: {
        wins: 6,
        losses: 9,
        goalsAgainst: 53,
        saves: 423,
        shotsAgainst: 476,
        svp: 0.889,
        shutouts: 0,
      },
    },
    {
      id: 'brain-reigns-binnington',
      name: 'Jordan Binnington',
      position: 'G',
      team: 'STL',
      rank: 292,
      startPercentage: 54,
      rosPercentage: 69,
      status: 'healthy',
      value: 58.0,
      stats: {
        wins: 5,
        losses: 5,
        goalsAgainst: 46,
        saves: 340,
        shotsAgainst: 386,
        svp: 0.881,
        shutouts: 0,
      },
    },
  ]

  return {
    id: 'brain-reigns',
    name: 'The Brain Reigns',
    owner: 'jreoch',
    record: '50-63-20',
    rank: 10,
    players,
  }
}

/**
 * Helper function to create Bye week team from Yahoo Sports data
 */
export function createByeWeekTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'bye-week-hertl',
      name: 'Tomas Hertl',
      position: 'C,LW',
      team: 'VGK',
      rank: 79,
      startPercentage: 72,
      rosPercentage: 90,
      status: 'healthy',
      value: 60.0,
      stats: {
        goals: 9,
        hockeyAssists: 9,
        hockeyPoints: 18,
        plusMinus: -1,
        pim: 8,
        ppp: 7,
        shp: 0,
        gwg: 1,
        sog: 63,
        fw: 222,
        hit: 26,
        blk: 10,
      },
    },
    {
      id: 'bye-week-hischier',
      name: 'Nico Hischier',
      position: 'C',
      team: 'NJ',
      rank: 54,
      startPercentage: 75,
      rosPercentage: 90,
      status: 'healthy',
      value: 68.0,
      stats: {
        goals: 8,
        hockeyAssists: 13,
        hockeyPoints: 21,
        plusMinus: 8,
        pim: 6,
        ppp: 5,
        shp: 0,
        gwg: 0,
        sog: 53,
        fw: 244,
        hit: 18,
        blk: 27,
      },
    },
    {
      id: 'bye-week-slafkovsky',
      name: 'Juraj Slafkovský',
      position: 'LW,RW',
      team: 'MTL',
      rank: 190,
      startPercentage: 40,
      rosPercentage: 75,
      status: 'healthy',
      value: 38.0,
      stats: {
        goals: 6,
        hockeyAssists: 4,
        hockeyPoints: 10,
        plusMinus: 3,
        pim: 16,
        ppp: 6,
        shp: 0,
        gwg: 0,
        sog: 46,
        fw: 4,
        hit: 40,
        blk: 20,
      },
    },
    {
      id: 'bye-week-boldy',
      name: 'Matt Boldy',
      position: 'LW,RW',
      team: 'MIN',
      rank: 12,
      startPercentage: 86,
      rosPercentage: 100,
      status: 'healthy',
      value: 88.0,
      stats: {
        goals: 14,
        hockeyAssists: 14,
        hockeyPoints: 28,
        plusMinus: 5,
        pim: 14,
        ppp: 12,
        shp: 1,
        gwg: 2,
        sog: 81,
        fw: 14,
        hit: 17,
        blk: 14,
      },
    },
    {
      id: 'bye-week-bratt',
      name: 'Jesper Bratt',
      position: 'LW,RW',
      team: 'NJ',
      rank: 75,
      startPercentage: 88,
      rosPercentage: 97,
      status: 'healthy',
      value: 62.0,
      stats: {
        goals: 5,
        hockeyAssists: 17,
        hockeyPoints: 22,
        plusMinus: 1,
        pim: 8,
        ppp: 6,
        shp: 1,
        gwg: 2,
        sog: 51,
        hit: 26,
        blk: 8,
      },
    },
    {
      id: 'bye-week-batherson',
      name: 'Drake Batherson',
      position: 'LW,RW',
      team: 'OTT',
      rank: 100,
      startPercentage: 70,
      rosPercentage: 89,
      status: 'healthy',
      value: 56.0,
      stats: {
        goals: 8,
        hockeyAssists: 13,
        hockeyPoints: 21,
        plusMinus: 7,
        pim: 6,
        ppp: 5,
        shp: 0,
        gwg: 2,
        sog: 41,
        fw: 1,
        hit: 32,
        blk: 8,
      },
    },
    // Defensemen
    {
      id: 'bye-week-lindell',
      name: 'Esa Lindell',
      position: 'D',
      team: 'DAL',
      rank: 306,
      startPercentage: 19,
      rosPercentage: 22,
      status: 'healthy',
      value: 22.0,
      stats: {
        goals: 3,
        hockeyAssists: 5,
        hockeyPoints: 8,
        plusMinus: 12,
        pim: 6,
        ppp: 0,
        shp: 0,
        gwg: 0,
        sog: 25,
        hit: 14,
        blk: 47,
      },
    },
    {
      id: 'bye-week-sergachev',
      name: 'Mikhail Sergachev',
      position: 'D',
      team: 'UTA',
      rank: 147,
      startPercentage: 92,
      rosPercentage: 96,
      status: 'healthy',
      value: 48.0,
      stats: {
        goals: 3,
        hockeyAssists: 13,
        hockeyPoints: 16,
        plusMinus: -4,
        pim: 16,
        ppp: 7,
        shp: 0,
        gwg: 0,
        sog: 52,
        hit: 6,
        blk: 41,
      },
    },
    {
      id: 'bye-week-makar',
      name: 'Cale Makar',
      position: 'D',
      team: 'COL',
      rank: 4,
      startPercentage: 95,
      rosPercentage: 100,
      status: 'healthy',
      value: 98.0,
      stats: {
        goals: 9,
        hockeyAssists: 21,
        hockeyPoints: 30,
        plusMinus: 24,
        pim: 10,
        ppp: 8,
        shp: 0,
        gwg: 3,
        sog: 66,
        hit: 13,
        blk: 41,
      },
    },
    // Util
    {
      id: 'bye-week-scheifele',
      name: 'Mark Scheifele',
      position: 'C',
      team: 'WPG',
      rank: 19,
      startPercentage: 80,
      rosPercentage: 99,
      status: 'healthy',
      value: 80.0,
      stats: {
        goals: 12,
        hockeyAssists: 17,
        hockeyPoints: 29,
        plusMinus: 7,
        pim: 16,
        ppp: 6,
        shp: 1,
        gwg: 2,
        sog: 52,
        fw: 184,
        hit: 5,
        blk: 6,
      },
    },
    // Bench
    {
      id: 'bye-week-kuzmenko',
      name: 'Andrei Kuzmenko',
      position: 'LW,RW',
      team: 'LA',
      rank: 554,
      startPercentage: 2,
      rosPercentage: 6,
      status: 'healthy',
      value: 8.0,
      stats: {
        goals: 3,
        hockeyAssists: 4,
        hockeyPoints: 7,
        plusMinus: -2,
        pim: 2,
        ppp: 3,
        shp: 0,
        gwg: 0,
        sog: 29,
        hit: 15,
        blk: 5,
      },
    },
    {
      id: 'bye-week-necas',
      name: 'Martin Necas',
      position: 'RW',
      team: 'COL',
      rank: 25,
      startPercentage: 85,
      rosPercentage: 99,
      status: 'healthy',
      value: 76.0,
      stats: {
        goals: 13,
        hockeyAssists: 17,
        hockeyPoints: 30,
        plusMinus: 21,
        pim: 16,
        ppp: 7,
        shp: 0,
        gwg: 0,
        sog: 49,
        fw: 7,
        hit: 22,
        blk: 9,
      },
    },
    {
      id: 'bye-week-raddysh',
      name: 'Darren Raddysh',
      position: 'D',
      team: 'TB',
      rank: 440,
      startPercentage: 21,
      rosPercentage: 23,
      status: 'healthy',
      value: 12.0,
      stats: {
        goals: 2,
        hockeyAssists: 8,
        hockeyPoints: 10,
        plusMinus: -3,
        pim: 9,
        ppp: 3,
        shp: 0,
        gwg: 0,
        sog: 32,
        hit: 12,
        blk: 14,
      },
    },
    // Goaltenders
    {
      id: 'bye-week-vejmelka',
      name: 'Karel Vejmelka',
      position: 'G',
      team: 'UTA',
      rank: 150,
      startPercentage: 56,
      rosPercentage: 70,
      status: 'healthy',
      value: 48.0,
      stats: {
        wins: 10,
        losses: 6,
        goalsAgainst: 51,
        saves: 389,
        shotsAgainst: 440,
        svp: 0.884,
        shutouts: 0,
      },
    },
    {
      id: 'bye-week-shesterkin',
      name: 'Igor Shesterkin',
      position: 'G',
      team: 'NYR',
      rank: 40,
      startPercentage: 92,
      rosPercentage: 99,
      status: 'healthy',
      value: 73.0,
      stats: {
        wins: 9,
        losses: 8,
        goalsAgainst: 47,
        saves: 484,
        shotsAgainst: 531,
        svp: 0.911,
        shutouts: 1,
      },
    },
    {
      id: 'bye-week-sorokin',
      name: 'Ilya Sorokin',
      position: 'G',
      team: 'NYI',
      rank: 77,
      startPercentage: 77,
      rosPercentage: 96,
      status: 'healthy',
      value: 64.0,
      stats: {
        wins: 7,
        losses: 7,
        goalsAgainst: 43,
        saves: 393,
        shotsAgainst: 436,
        svp: 0.901,
        shutouts: 2,
      },
    },
  ]

  return {
    id: 'bye-week',
    name: 'Bye week',
    owner: 'Justin',
    record: '70-42-21',
    rank: 1,
    players,
  }
}

/**
 * Helper function to create Goon Squad team from Yahoo Sports data
 */
export function createGoonSquadTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'goon-squad-strome',
      name: 'Dylan Strome',
      position: 'C',
      team: 'WSH',
      rank: 81,
      startPercentage: 65,
      rosPercentage: 88,
      status: 'healthy',
      value: 58.0,
      stats: {
        goals: 5,
        hockeyAssists: 15,
        hockeyPoints: 20,
        plusMinus: 12,
        pim: 12,
        ppp: 6,
        shp: 0,
        gwg: 1,
        sog: 38,
        fw: 214,
        hit: 7,
        blk: 10,
      },
    },
    {
      id: 'goon-squad-kastelic',
      name: 'Mark Kastelic',
      position: 'C,RW',
      team: 'BOS',
      rank: 121,
      startPercentage: 10,
      rosPercentage: 14,
      status: 'healthy',
      value: 25.0,
      stats: {
        goals: 4,
        hockeyAssists: 4,
        hockeyPoints: 8,
        plusMinus: 4,
        pim: 31,
        ppp: 1,
        shp: 0,
        gwg: 1,
        sog: 34,
        fw: 116,
        hit: 59,
        blk: 29,
      },
    },
    {
      id: 'goon-squad-debrincat',
      name: 'Alex DeBrincat',
      position: 'LW,RW',
      team: 'DET',
      rank: 36,
      startPercentage: 89,
      rosPercentage: 96,
      status: 'healthy',
      value: 78.0,
      stats: {
        goals: 12,
        hockeyAssists: 14,
        hockeyPoints: 26,
        plusMinus: -3,
        pim: 6,
        ppp: 10,
        shp: 0,
        gwg: 2,
        sog: 92,
        fw: 4,
        hit: 11,
        blk: 8,
      },
    },
    {
      id: 'goon-squad-haula',
      name: 'Erik Haula',
      position: 'C,LW',
      team: 'NSH',
      rank: 231,
      startPercentage: 2,
      rosPercentage: 2,
      status: 'healthy',
      value: 15.0,
      stats: {
        goals: 4,
        hockeyAssists: 9,
        hockeyPoints: 13,
        plusMinus: -8,
        pim: 18,
        ppp: 5,
        shp: 0,
        gwg: 0,
        sog: 31,
        fw: 132,
        hit: 34,
        blk: 11,
      },
    },
    {
      id: 'goon-squad-zibanejad',
      name: 'Mika Zibanejad',
      position: 'C,RW',
      team: 'NYR',
      rank: 72,
      startPercentage: 58,
      rosPercentage: 75,
      status: 'healthy',
      value: 62.0,
      stats: {
        goals: 7,
        hockeyAssists: 9,
        hockeyPoints: 16,
        plusMinus: -9,
        pim: 6,
        ppp: 7,
        shp: 1,
        gwg: 1,
        sog: 74,
        fw: 179,
        hit: 33,
        blk: 19,
      },
    },
    {
      id: 'goon-squad-wilson',
      name: 'Tom Wilson',
      position: 'RW',
      team: 'WSH',
      rank: 9,
      startPercentage: 80,
      rosPercentage: 92,
      status: 'healthy',
      value: 85.0,
      stats: {
        goals: 12,
        hockeyAssists: 12,
        hockeyPoints: 24,
        plusMinus: 11,
        pim: 52,
        ppp: 6,
        shp: 0,
        gwg: 1,
        sog: 52,
        fw: 7,
        hit: 66,
        blk: 15,
      },
    },
    // Defensemen
    {
      id: 'goon-squad-morrissey',
      name: 'Josh Morrissey',
      position: 'D',
      team: 'WPG',
      rank: 66,
      startPercentage: 95,
      rosPercentage: 99,
      status: 'healthy',
      value: 65.0,
      stats: {
        goals: 5,
        hockeyAssists: 18,
        hockeyPoints: 23,
        plusMinus: 9,
        pim: 6,
        ppp: 7,
        shp: 0,
        gwg: 0,
        sog: 38,
        hit: 13,
        blk: 46,
      },
    },
    {
      id: 'goon-squad-zadorov',
      name: 'Nikita Zadorov',
      position: 'D',
      team: 'BOS',
      rank: 110,
      startPercentage: 41,
      rosPercentage: 45,
      status: 'healthy',
      value: 42.0,
      stats: {
        goals: 1,
        hockeyAssists: 7,
        hockeyPoints: 8,
        plusMinus: 4,
        pim: 46,
        ppp: 0,
        shp: 0,
        gwg: 0,
        sog: 32,
        hit: 78,
        blk: 36,
      },
    },
    {
      id: 'goon-squad-gudas',
      name: 'Radko Gudas',
      position: 'D',
      team: 'ANA',
      rank: 536,
      startPercentage: 19,
      rosPercentage: 23,
      status: 'healthy',
      value: 10.0,
      stats: {
        goals: 1,
        hockeyAssists: 2,
        hockeyPoints: 3,
        plusMinus: -3,
        pim: 7,
        ppp: 0,
        shp: 0,
        gwg: 0,
        sog: 20,
        hit: 42,
        blk: 23,
      },
    },
    // Util
    {
      id: 'goon-squad-oreilly',
      name: "Ryan O'Reilly",
      position: 'C',
      team: 'NSH',
      rank: 108,
      startPercentage: 12,
      rosPercentage: 17,
      status: 'healthy',
      value: 30.0,
      stats: {
        goals: 7,
        hockeyAssists: 9,
        hockeyPoints: 16,
        plusMinus: 0,
        pim: 0,
        ppp: 2,
        shp: 1,
        gwg: 3,
        sog: 39,
        fw: 237,
        hit: 7,
        blk: 18,
      },
    },
    // Bench
    {
      id: 'goon-squad-lindholm',
      name: 'Elias Lindholm',
      position: 'C',
      team: 'BOS',
      rank: 298,
      startPercentage: 12,
      rosPercentage: 30,
      status: 'healthy',
      value: 22.0,
      stats: {
        goals: 4,
        hockeyAssists: 5,
        hockeyPoints: 9,
        plusMinus: -4,
        pim: 8,
        ppp: 7,
        shp: 0,
        gwg: 1,
        sog: 23,
        fw: 145,
        hit: 20,
        blk: 15,
      },
    },
    // IR
    {
      id: 'goon-squad-tkachuk',
      name: 'Brady Tkachuk',
      position: 'C,LW',
      team: 'OTT',
      rank: 696,
      startPercentage: 16,
      rosPercentage: 98,
      status: 'IR',
      value: 70.0,
      stats: {
        goals: 0,
        hockeyAssists: 3,
        hockeyPoints: 3,
        plusMinus: 1,
        pim: 4,
        ppp: 1,
        shp: 0,
        gwg: 0,
        sog: 10,
        fw: 8,
        hit: 10,
        blk: 0,
      },
    },
    // IR+
    {
      id: 'goon-squad-rempe',
      name: 'Matt Rempe',
      position: 'RW',
      team: 'NYR',
      rank: 679,
      startPercentage: 0,
      rosPercentage: 1,
      status: 'IR-LT',
      value: 5.0,
      stats: {
        goals: 1,
        hockeyAssists: 0,
        hockeyPoints: 1,
        plusMinus: 1,
        pim: 7,
        ppp: 0,
        shp: 0,
        gwg: 0,
        sog: 8,
        fw: 2,
        hit: 30,
        blk: 2,
      },
    },
    // Goaltenders
    {
      id: 'goon-squad-blackwood',
      name: 'Mackenzie Blackwood',
      position: 'G',
      team: 'COL',
      rank: 59,
      startPercentage: 71,
      rosPercentage: 95,
      status: 'healthy',
      value: 70.0,
      stats: {
        wins: 4,
        losses: 0,
        goalsAgainst: 10,
        saves: 128,
        shotsAgainst: 138,
        svp: 0.928,
        shutouts: 2,
      },
    },
    {
      id: 'goon-squad-schmid',
      name: 'Akira Schmid',
      position: 'G',
      team: 'VGK',
      rank: 55,
      startPercentage: 47,
      rosPercentage: 54,
      status: 'healthy',
      value: 55.0,
      stats: {
        wins: 9,
        losses: 1,
        goalsAgainst: 34,
        saves: 306,
        shotsAgainst: 340,
        svp: 0.900,
        shutouts: 1,
      },
    },
    {
      id: 'goon-squad-wedgewood',
      name: 'Scott Wedgewood',
      position: 'G',
      team: 'COL',
      rank: 11,
      startPercentage: 54,
      rosPercentage: 89,
      status: 'healthy',
      value: 85.0,
      stats: {
        wins: 13,
        losses: 1,
        goalsAgainst: 34,
        saves: 381,
        shotsAgainst: 415,
        svp: 0.918,
        shutouts: 1,
      },
    },
    {
      id: 'goon-squad-silovs',
      name: 'Arturs Silovs',
      position: 'G',
      team: 'PIT',
      rank: 120,
      startPercentage: 10,
      rosPercentage: 26,
      status: 'healthy',
      value: 40.0,
      stats: {
        wins: 4,
        losses: 3,
        goalsAgainst: 29,
        saves: 284,
        shotsAgainst: 313,
        svp: 0.907,
        shutouts: 1,
      },
    },
    {
      id: 'goon-squad-hill',
      name: 'Adin Hill',
      position: 'G',
      team: 'VGK',
      rank: 251,
      startPercentage: 15,
      rosPercentage: 74,
      status: 'IR',
      value: 50.0,
      stats: {
        wins: 1,
        losses: 0,
        goalsAgainst: 10,
        saves: 79,
        shotsAgainst: 89,
        svp: 0.888,
        shutouts: 0,
      },
    },
  ]

  return {
    id: 'goon-squad',
    name: 'Goon Squad',
    owner: 'Jason',
    record: '56-56-21',
    rank: 4,
    players,
  }
}

/**
 * Helper function to create Ike and Ike team from Yahoo Sports data
 */
export function createIkeAndIkeTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'ike-eichel',
      name: 'Jack Eichel',
      position: 'C',
      team: 'VGK',
      rank: 10,
      startPercentage: 94,
      rosPercentage: 100,
      status: 'healthy',
      value: 90.0,
      stats: {
        goals: 11,
        hockeyAssists: 20,
        hockeyPoints: 31,
        plusMinus: 4,
        pim: 2,
        ppp: 12,
        shp: 0,
        gwg: 2,
        sog: 94,
        fw: 179,
        hit: 8,
        blk: 14,
      },
    },
    {
      id: 'ike-hintz',
      name: 'Roope Hintz',
      position: 'C',
      team: 'DAL',
      rank: 92,
      startPercentage: 73,
      rosPercentage: 91,
      status: 'healthy',
      value: 65.0,
      stats: {
        goals: 7,
        hockeyAssists: 12,
        hockeyPoints: 19,
        plusMinus: 6,
        pim: 4,
        ppp: 9,
        shp: 0,
        gwg: 1,
        sog: 53,
        fw: 157,
        hit: 15,
        blk: 8,
      },
    },
    {
      id: 'ike-knies',
      name: 'Matthew Knies',
      position: 'LW',
      team: 'TOR',
      rank: 124,
      startPercentage: 50,
      rosPercentage: 93,
      status: 'healthy',
      value: 55.0,
      stats: {
        goals: 5,
        hockeyAssists: 18,
        hockeyPoints: 23,
        plusMinus: 3,
        pim: 8,
        ppp: 2,
        shp: 0,
        gwg: 0,
        sog: 44,
        hit: 53,
        blk: 9,
      },
    },
    {
      id: 'ike-connor',
      name: 'Kyle Connor',
      position: 'LW',
      team: 'WPG',
      rank: 27,
      startPercentage: 85,
      rosPercentage: 100,
      status: 'healthy',
      value: 82.0,
      stats: {
        goals: 11,
        hockeyAssists: 17,
        hockeyPoints: 28,
        plusMinus: 6,
        pim: 6,
        ppp: 7,
        shp: 2,
        gwg: 1,
        sog: 78,
        hit: 9,
        blk: 3,
      },
    },
    {
      id: 'ike-raymond',
      name: 'Lucas Raymond',
      position: 'RW',
      team: 'DET',
      rank: 73,
      startPercentage: 83,
      rosPercentage: 92,
      status: 'healthy',
      value: 70.0,
      stats: {
        goals: 7,
        hockeyAssists: 18,
        hockeyPoints: 25,
        plusMinus: 5,
        pim: 4,
        ppp: 8,
        shp: 0,
        gwg: 2,
        sog: 54,
        fw: 1,
        hit: 8,
        blk: 9,
      },
    },
    {
      id: 'ike-marner',
      name: 'Mitch Marner',
      position: 'RW',
      team: 'VGK',
      rank: 156,
      startPercentage: 90,
      rosPercentage: 99,
      status: 'healthy',
      value: 75.0,
      stats: {
        goals: 4,
        hockeyAssists: 18,
        hockeyPoints: 22,
        plusMinus: 6,
        pim: 6,
        ppp: 5,
        shp: 0,
        gwg: 0,
        sog: 43,
        fw: 14,
        hit: 9,
        blk: 13,
      },
    },
    // Defensemen
    {
      id: 'ike-theodore',
      name: 'Shea Theodore',
      position: 'D',
      team: 'VGK',
      rank: 177,
      startPercentage: 92,
      rosPercentage: 95,
      status: 'healthy',
      value: 58.0,
      stats: {
        goals: 3,
        hockeyAssists: 11,
        hockeyPoints: 14,
        plusMinus: 4,
        pim: 4,
        ppp: 4,
        shp: 0,
        gwg: 1,
        sog: 55,
        hit: 1,
        blk: 35,
      },
    },
    {
      id: 'ike-l-hughes',
      name: 'Luke Hughes',
      position: 'D',
      team: 'NJ',
      rank: 215,
      startPercentage: 82,
      rosPercentage: 87,
      status: 'healthy',
      value: 50.0,
      stats: {
        goals: 1,
        hockeyAssists: 13,
        hockeyPoints: 14,
        plusMinus: 0,
        pim: 22,
        ppp: 4,
        shp: 0,
        gwg: 0,
        sog: 48,
        hit: 8,
        blk: 21,
      },
    },
    {
      id: 'ike-carlson',
      name: 'John Carlson',
      position: 'D',
      team: 'WSH',
      rank: 95,
      startPercentage: 90,
      rosPercentage: 94,
      status: 'healthy',
      value: 68.0,
      stats: {
        goals: 6,
        hockeyAssists: 16,
        hockeyPoints: 22,
        plusMinus: 8,
        pim: 6,
        ppp: 5,
        shp: 0,
        gwg: 0,
        sog: 54,
        hit: 9,
        blk: 32,
      },
    },
    // Util
    {
      id: 'ike-tuch',
      name: 'Alex Tuch',
      position: 'RW',
      team: 'BUF',
      rank: 62,
      startPercentage: 59,
      rosPercentage: 85,
      status: 'healthy',
      value: 60.0,
      stats: {
        goals: 8,
        hockeyAssists: 13,
        hockeyPoints: 21,
        plusMinus: 1,
        pim: 33,
        ppp: 2,
        shp: 1,
        gwg: 0,
        sog: 52,
        fw: 9,
        hit: 22,
        blk: 23,
      },
    },
    // Bench
    {
      id: 'ike-point',
      name: 'Brayden Point',
      position: 'C',
      team: 'TB',
      rank: 454,
      startPercentage: 39,
      rosPercentage: 97,
      status: 'DTD',
      value: 72.0,
      stats: {
        goals: 3,
        hockeyAssists: 8,
        hockeyPoints: 11,
        plusMinus: -11,
        pim: 6,
        ppp: 3,
        shp: 0,
        gwg: 0,
        sog: 44,
        fw: 105,
        hit: 3,
        blk: 8,
      },
    },
    // Goaltenders
    {
      id: 'ike-bobrovsky',
      name: 'Sergei Bobrovsky',
      position: 'G',
      team: 'FLA',
      rank: 115,
      startPercentage: 90,
      rosPercentage: 99,
      status: 'healthy',
      value: 70.0,
      stats: {
        wins: 10,
        losses: 7,
        goalsAgainst: 47,
        saves: 352,
        shotsAgainst: 399,
        svp: 0.882,
        shutouts: 2,
      },
    },
    {
      id: 'ike-markstrom',
      name: 'Jacob Markstrom',
      position: 'G',
      team: 'NJ',
      rank: 342,
      startPercentage: 68,
      rosPercentage: 79,
      status: 'healthy',
      value: 58.0,
      stats: {
        wins: 7,
        losses: 3,
        goalsAgainst: 37,
        saves: 257,
        shotsAgainst: 294,
        svp: 0.874,
        shutouts: 0,
      },
    },
    {
      id: 'ike-talbot',
      name: 'Cam Talbot',
      position: 'G',
      team: 'DET',
      rank: 175,
      startPercentage: 21,
      rosPercentage: 28,
      status: 'healthy',
      value: 45.0,
      stats: {
        wins: 9,
        losses: 4,
        goalsAgainst: 38,
        saves: 298,
        shotsAgainst: 336,
        svp: 0.887,
        shutouts: 0,
      },
    },
    {
      id: 'ike-skinner',
      name: 'Stuart Skinner',
      position: 'G',
      team: 'EDM',
      rank: 200,
      startPercentage: 18,
      rosPercentage: 54,
      status: 'healthy',
      value: 50.0,
      stats: {
        wins: 8,
        losses: 7,
        goalsAgainst: 54,
        saves: 389,
        shotsAgainst: 443,
        svp: 0.878,
        shutouts: 1,
      },
    },
    {
      id: 'ike-luukkonen',
      name: 'Ukko-Pekka Luukkonen',
      position: 'G',
      team: 'BUF',
      rank: 265,
      startPercentage: 20,
      rosPercentage: 27,
      status: 'healthy',
      value: 40.0,
      stats: {
        wins: 3,
        losses: 3,
        goalsAgainst: 19,
        saves: 155,
        shotsAgainst: 174,
        svp: 0.891,
        shutouts: 0,
      },
    },
    {
      id: 'ike-stolarz',
      name: 'Anthony Stolarz',
      position: 'G',
      team: 'TOR',
      rank: 318,
      startPercentage: 13,
      rosPercentage: 74,
      status: 'IR',
      value: 52.0,
      stats: {
        wins: 6,
        losses: 5,
        goalsAgainst: 41,
        saves: 312,
        shotsAgainst: 353,
        svp: 0.884,
        shutouts: 0,
      },
    },
  ]

  return {
    id: 'ike-and-ike',
    name: 'Ike and Ike',
    owner: 'Ike',
    record: '56-64-13',
    rank: 7,
    players,
  }
}

/**
 * Helper function to create Inglorious Bastards team from Yahoo Sports data
 */
export function createIngloriousBastardsTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'bastards-nylander',
      name: 'William Nylander',
      position: 'C,RW',
      team: 'TOR',
      rank: 14,
      startPercentage: 78,
      rosPercentage: 100,
      status: 'healthy',
      value: 92.0,
    },
    {
      id: 'bastards-mcleod',
      name: 'Ryan McLeod',
      position: 'C',
      team: 'BUF',
      rank: 468,
      startPercentage: 2,
      rosPercentage: 3,
      status: 'healthy',
      value: 12.0,
    },
    {
      id: 'bastards-svechnikov',
      name: 'Andrei Svechnikov',
      position: 'LW,RW',
      team: 'CAR',
      rank: 113,
      startPercentage: 43,
      rosPercentage: 66,
      status: 'healthy',
      value: 48.0,
    },
    {
      id: 'bastards-guentzel',
      name: 'Jake Guentzel',
      position: 'LW',
      team: 'TB',
      rank: 29,
      startPercentage: 93,
      rosPercentage: 99,
      status: 'healthy',
      value: 84.0,
    },
    {
      id: 'bastards-smith',
      name: 'Will Smith',
      position: 'C,RW',
      team: 'SJ',
      rank: 140,
      startPercentage: 39,
      rosPercentage: 67,
      status: 'healthy',
      value: 42.0,
    },
    {
      id: 'bastards-pastrnak',
      name: 'David Pastrnak',
      position: 'RW',
      team: 'BOS',
      rank: 10,
      startPercentage: 88,
      rosPercentage: 100,
      status: 'healthy',
      value: 96.0,
    },
    // Defensemen
    {
      id: 'bastards-gostisbehere',
      name: 'Shayne Gostisbehere',
      position: 'D',
      team: 'CAR',
      rank: 156,
      startPercentage: 73,
      rosPercentage: 84,
      status: 'healthy',
      value: 46.0,
    },
    {
      id: 'bastards-trouba',
      name: 'Jacob Trouba',
      position: 'D',
      team: 'ANA',
      rank: 248,
      startPercentage: 69,
      rosPercentage: 80,
      status: 'healthy',
      value: 30.0,
    },
    {
      id: 'bastards-faulk',
      name: 'Justin Faulk',
      position: 'D',
      team: 'STL',
      rank: 205,
      startPercentage: 56,
      rosPercentage: 62,
      status: 'healthy',
      value: 35.0,
    },
    // Util
    {
      id: 'bastards-horvat',
      name: 'Bo Horvat',
      position: 'C',
      team: 'NYI',
      rank: 117,
      startPercentage: 66,
      rosPercentage: 92,
      status: 'healthy',
      value: 52.0,
    },
    // Bench
    {
      id: 'bastards-nurse',
      name: 'Darnell Nurse',
      position: 'D',
      team: 'EDM',
      rank: 260,
      startPercentage: 36,
      rosPercentage: 70,
      status: 'healthy',
      value: 28.0,
    },
    {
      id: 'bastards-jarvis',
      name: 'Seth Jarvis',
      position: 'C,LW,RW',
      team: 'CAR',
      rank: 73,
      startPercentage: 70,
      rosPercentage: 96,
      status: 'healthy',
      value: 62.0,
    },
    {
      id: 'bastards-johnston',
      name: 'Wyatt Johnston',
      position: 'C,RW',
      team: 'DAL',
      rank: 53,
      startPercentage: 90,
      rosPercentage: 97,
      status: 'healthy',
      value: 68.0,
    },
    // Goaltenders
    {
      id: 'bastards-desmith',
      name: 'Casey DeSmith',
      position: 'G',
      team: 'DAL',
      rank: 334,
      startPercentage: 18,
      rosPercentage: 20,
      status: 'healthy',
      value: 15.0,
    },
    {
      id: 'bastards-ullmark',
      name: 'Linus Ullmark',
      position: 'G',
      team: 'OTT',
      rank: 98,
      startPercentage: 69,
      rosPercentage: 83,
      status: 'healthy',
      value: 60.0,
    },
    {
      id: 'bastards-kuemper',
      name: 'Darcy Kuemper',
      position: 'G',
      team: 'LA',
      rank: 56,
      startPercentage: 43,
      rosPercentage: 95,
      status: 'healthy',
      value: 72.0,
    },
    {
      id: 'bastards-demko',
      name: 'Thatcher Demko',
      position: 'G',
      team: 'VAN',
      rank: 178,
      startPercentage: 8,
      rosPercentage: 73,
      status: 'IR',
      value: 55.0,
    },
  ]

  return {
    id: 'inglorious-bastards',
    name: 'Inglorious Bastards',
    owner: 'Tom',
    record: '54-64-15',
    rank: 9,
    players,
  }
}

/**
 * Helper function to create mismanagewhome? team from Yahoo Sports data
 */
export function createMismanagewhomeTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'mismanage-mackinnon',
      name: 'Nathan MacKinnon',
      position: 'C',
      team: 'COL',
      rank: 1,
      startPercentage: 86,
      rosPercentage: 100,
      status: 'healthy',
      value: 100.0,
      stats: {
        goals: 18,
        hockeyAssists: 21,
        hockeyPoints: 39,
        plusMinus: 26,
        pim: 12,
        ppp: 10,
        shp: 0,
        gwg: 2,
        sog: 99,
        fw: 236,
        hit: 18,
        blk: 16,
      },
    },
    {
      id: 'mismanage-larkin',
      name: 'Dylan Larkin',
      position: 'C',
      team: 'DET',
      rank: 7,
      startPercentage: 86,
      rosPercentage: 97,
      status: 'healthy',
      value: 96.0,
      stats: {
        goals: 13,
        hockeyAssists: 13,
        hockeyPoints: 26,
        plusMinus: 8,
        pim: 22,
        ppp: 6,
        shp: 0,
        gwg: 3,
        sog: 81,
        fw: 287,
        hit: 9,
        blk: 11,
      },
    },
    {
      id: 'mismanage-lehkonen',
      name: 'Artturi Lehkonen',
      position: 'LW,RW',
      team: 'COL',
      rank: 103,
      startPercentage: 61,
      rosPercentage: 83,
      status: 'healthy',
      value: 50.0,
      stats: {
        goals: 9,
        hockeyAssists: 12,
        hockeyPoints: 21,
        plusMinus: 21,
        pim: 2,
        ppp: 2,
        shp: 0,
        gwg: 0,
        sog: 62,
        hit: 12,
        blk: 19,
      },
    },
    {
      id: 'mismanage-marchand',
      name: 'Brad Marchand',
      position: 'LW,RW',
      team: 'FLA',
      rank: 63,
      startPercentage: 75,
      rosPercentage: 91,
      status: 'healthy',
      value: 65.0,
      stats: {
        goals: 14,
        hockeyAssists: 12,
        hockeyPoints: 26,
        plusMinus: -6,
        pim: 18,
        ppp: 8,
        shp: 0,
        gwg: 1,
        sog: 62,
        fw: 1,
        hit: 16,
        blk: 8,
      },
    },
    {
      id: 'mismanage-hagel',
      name: 'Brandon Hagel',
      position: 'LW,RW',
      team: 'TB',
      rank: 26,
      startPercentage: 87,
      rosPercentage: 97,
      status: 'healthy',
      value: 85.0,
      stats: {
        goals: 12,
        hockeyAssists: 12,
        hockeyPoints: 24,
        plusMinus: 12,
        pim: 12,
        ppp: 3,
        shp: 1,
        gwg: 3,
        sog: 65,
        fw: 13,
        hit: 13,
        blk: 13,
      },
    },
    {
      id: 'mismanage-reinhart',
      name: 'Sam Reinhart',
      position: 'C,RW',
      team: 'FLA',
      rank: 32,
      startPercentage: 91,
      rosPercentage: 99,
      status: 'healthy',
      value: 80.0,
      stats: {
        goals: 13,
        hockeyAssists: 8,
        hockeyPoints: 21,
        plusMinus: -10,
        pim: 2,
        ppp: 8,
        shp: 1,
        gwg: 5,
        sog: 64,
        fw: 22,
        hit: 22,
        blk: 18,
      },
    },
    // Defensemen
    {
      id: 'mismanage-bouchard',
      name: 'Evan Bouchard',
      position: 'D',
      team: 'EDM',
      rank: 85,
      startPercentage: 62,
      rosPercentage: 100,
      status: 'healthy',
      value: 72.0,
      stats: {
        goals: 4,
        hockeyAssists: 17,
        hockeyPoints: 21,
        plusMinus: -1,
        pim: 10,
        ppp: 5,
        shp: 0,
        gwg: 1,
        sog: 68,
        hit: 9,
        blk: 32,
      },
    },
    {
      id: 'mismanage-schaefer',
      name: 'Matthew Schaefer',
      position: 'D',
      team: 'NYI',
      rank: 74,
      startPercentage: 86,
      rosPercentage: 94,
      status: 'healthy',
      value: 68.0,
      stats: {
        goals: 7,
        hockeyAssists: 9,
        hockeyPoints: 16,
        plusMinus: 8,
        pim: 8,
        ppp: 7,
        shp: 0,
        gwg: 2,
        sog: 71,
        hit: 11,
        blk: 27,
      },
    },
    {
      id: 'mismanage-seider',
      name: 'Moritz Seider',
      position: 'D',
      team: 'DET',
      rank: 51,
      startPercentage: 95,
      rosPercentage: 98,
      status: 'healthy',
      value: 75.0,
      stats: {
        goals: 3,
        hockeyAssists: 13,
        hockeyPoints: 16,
        plusMinus: 2,
        pim: 18,
        ppp: 8,
        shp: 0,
        gwg: 0,
        sog: 61,
        hit: 43,
        blk: 48,
      },
    },
    // Util
    {
      id: 'mismanage-bertuzzi',
      name: 'Tyler Bertuzzi',
      position: 'LW,RW',
      team: 'CHI',
      rank: 94,
      startPercentage: 43,
      rosPercentage: 63,
      status: 'healthy',
      value: 55.0,
      stats: {
        goals: 12,
        hockeyAssists: 8,
        hockeyPoints: 20,
        plusMinus: 0,
        pim: 22,
        ppp: 10,
        shp: 0,
        gwg: 1,
        sog: 46,
        fw: 20,
        hit: 20,
        blk: 1,
      },
    },
    // Bench
    {
      id: 'mismanage-nugent-hopkins',
      name: 'Ryan Nugent-Hopkins',
      position: 'C,LW',
      team: 'EDM',
      rank: 392,
      startPercentage: 4,
      rosPercentage: 67,
      status: 'IR',
      value: 65.0,
      stats: {
        goals: 5,
        hockeyAssists: 11,
        hockeyPoints: 16,
        plusMinus: -11,
        pim: 4,
        ppp: 9,
        shp: 0,
        gwg: 0,
        sog: 23,
        fw: 38,
        hit: 7,
        blk: 4,
      },
    },
    {
      id: 'mismanage-mcdavid',
      name: 'Connor McDavid',
      position: 'C',
      team: 'EDM',
      rank: 18,
      startPercentage: 32,
      rosPercentage: 100,
      status: 'healthy',
      value: 98.0,
      stats: {
        goals: 10,
        hockeyAssists: 24,
        hockeyPoints: 34,
        plusMinus: -6,
        pim: 10,
        ppp: 13,
        shp: 1,
        gwg: 0,
        sog: 73,
        fw: 123,
        hit: 9,
        blk: 6,
      },
    },
    // IR
    {
      id: 'mismanage-barkov',
      name: 'Aleksander Barkov',
      position: 'C',
      team: 'FLA',
      rank: 1241,
      startPercentage: 2,
      rosPercentage: 22,
      status: 'IR',
      value: 40.0,
    },
    // IR+
    {
      id: 'mismanage-stone',
      name: 'Mark Stone',
      position: 'RW',
      team: 'VGK',
      rank: 327,
      startPercentage: 25,
      rosPercentage: 78,
      status: 'healthy',
      value: 45.0,
      stats: {
        goals: 3,
        hockeyAssists: 11,
        hockeyPoints: 14,
        plusMinus: 2,
        pim: 0,
        ppp: 9,
        shp: 1,
        gwg: 0,
        sog: 22,
        hit: 5,
        blk: 5,
      },
    },
    // Goaltenders
    {
      id: 'mismanage-askarov',
      name: 'Yaroslav Askarov',
      position: 'G',
      team: 'SJ',
      rank: 125,
      startPercentage: 49,
      rosPercentage: 71,
      status: 'healthy',
      value: 60.0,
      stats: {
        wins: 8,
        losses: 6,
        goalsAgainst: 44,
        saves: 421,
        shotsAgainst: 465,
        svp: 0.905,
        shutouts: 0,
      },
    },
    {
      id: 'mismanage-wolf',
      name: 'Dustin Wolf',
      position: 'G',
      team: 'CGY',
      rank: 224,
      startPercentage: 61,
      rosPercentage: 86,
      status: 'healthy',
      value: 55.0,
      stats: {
        wins: 6,
        losses: 12,
        goalsAgainst: 57,
        saves: 461,
        shotsAgainst: 518,
        svp: 0.890,
        shutouts: 1,
      },
    },
    {
      id: 'mismanage-andersen',
      name: 'Frederik Andersen',
      position: 'G',
      team: 'CAR',
      rank: 324,
      startPercentage: 32,
      rosPercentage: 50,
      status: 'healthy',
      value: 50.0,
      stats: {
        wins: 5,
        losses: 6,
        goalsAgainst: 40,
        saves: 288,
        shotsAgainst: 328,
        svp: 0.878,
        shutouts: 0,
      },
    },
    {
      id: 'mismanage-comrie',
      name: 'Eric Comrie',
      position: 'G',
      team: 'WPG',
      rank: 250,
      startPercentage: 22,
      rosPercentage: 33,
      status: 'healthy',
      value: 42.0,
      stats: {
        wins: 4,
        losses: 4,
        goalsAgainst: 24,
        saves: 209,
        shotsAgainst: 233,
        svp: 0.897,
        shutouts: 0,
      },
    },
  ]

  return {
    id: 'mismanagewhome',
    name: 'mismanagewhome?',
    owner: 'eric',
    record: '64-52-17',
    rank: 2,
    players,
  }
}

/**
 * Helper function to create Zoey team from Yahoo Sports data
 */
export function createZoeyTeam(): Team {
  const players: Player[] = [
    // Forwards
    {
      id: 'zoey-trocheck',
      name: 'Vincent Trocheck',
      position: 'C',
      team: 'NYR',
      rank: 345,
      startPercentage: 47,
      rosPercentage: 64,
      status: 'healthy',
      value: 45.0,
      stats: {
        goals: 5,
        hockeyAssists: 4,
        hockeyPoints: 9,
        plusMinus: 1,
        pim: 8,
        ppp: 1,
        shp: 0,
        gwg: 1,
        sog: 14,
        fw: 107,
        hit: 43,
        blk: 10,
      },
    },
    {
      id: 'zoey-tavares',
      name: 'John Tavares',
      position: 'C',
      team: 'TOR',
      rank: 30,
      startPercentage: 69,
      rosPercentage: 96,
      status: 'healthy',
      value: 82.0,
      stats: {
        goals: 12,
        hockeyAssists: 16,
        hockeyPoints: 28,
        plusMinus: 4,
        pim: 6,
        ppp: 4,
        shp: 0,
        gwg: 1,
        sog: 69,
        fw: 238,
        hit: 24,
        blk: 5,
      },
    },
    {
      id: 'zoey-voronkov',
      name: 'Dmitri Voronkov',
      position: 'LW',
      team: 'CBJ',
      rank: 122,
      startPercentage: 34,
      rosPercentage: 44,
      status: 'healthy',
      value: 52.0,
      stats: {
        goals: 9,
        hockeyAssists: 9,
        hockeyPoints: 18,
        plusMinus: 5,
        pim: 24,
        ppp: 3,
        shp: 0,
        gwg: 0,
        sog: 48,
        fw: 3,
        hit: 43,
        blk: 6,
      },
    },
    {
      id: 'zoey-pettersson',
      name: 'Elias Pettersson',
      position: 'C,LW',
      team: 'VAN',
      rank: 33,
      startPercentage: 72,
      rosPercentage: 92,
      status: 'healthy',
      value: 78.0,
      stats: {
        goals: 7,
        hockeyAssists: 14,
        hockeyPoints: 21,
        plusMinus: -5,
        pim: 6,
        ppp: 8,
        shp: 1,
        gwg: 0,
        sog: 42,
        fw: 253,
        hit: 25,
        blk: 46,
      },
    },
    {
      id: 'zoey-meier',
      name: 'Timo Meier',
      position: 'LW,RW',
      team: 'NJ',
      rank: 64,
      startPercentage: 78,
      rosPercentage: 88,
      status: 'healthy',
      value: 68.0,
      stats: {
        goals: 8,
        hockeyAssists: 11,
        hockeyPoints: 19,
        plusMinus: 3,
        pim: 10,
        ppp: 7,
        shp: 0,
        gwg: 1,
        sog: 75,
        fw: 18,
        hit: 42,
        blk: 14,
      },
    },
    {
      id: 'zoey-keller',
      name: 'Clayton Keller',
      position: 'LW,RW',
      team: 'UTA',
      rank: 96,
      startPercentage: 88,
      rosPercentage: 98,
      status: 'healthy',
      value: 58.0,
      stats: {
        goals: 8,
        hockeyAssists: 13,
        hockeyPoints: 21,
        plusMinus: 0,
        pim: 8,
        ppp: 7,
        shp: 0,
        gwg: 2,
        sog: 68,
        fw: 3,
        hit: 5,
        blk: 11,
      },
    },
    // Defensemen
    {
      id: 'zoey-dobson',
      name: 'Noah Dobson',
      position: 'D',
      team: 'MTL',
      rank: 158,
      startPercentage: 87,
      rosPercentage: 97,
      status: 'healthy',
      value: 65.0,
      stats: {
        goals: 3,
        hockeyAssists: 13,
        hockeyPoints: 16,
        plusMinus: 2,
        pim: 10,
        ppp: 2,
        shp: 0,
        gwg: 1,
        sog: 38,
        hit: 9,
        blk: 43,
      },
    },
    {
      id: 'zoey-hughes',
      name: 'Quinn Hughes',
      position: 'D',
      team: 'VAN',
      rank: 131,
      startPercentage: 96,
      rosPercentage: 100,
      status: 'healthy',
      value: 72.0,
      stats: {
        goals: 2,
        hockeyAssists: 20,
        hockeyPoints: 22,
        plusMinus: -5,
        pim: 6,
        ppp: 11,
        shp: 0,
        gwg: 0,
        sog: 53,
        hit: 1,
        blk: 23,
      },
    },
    {
      id: 'zoey-karlsson',
      name: 'Erik Karlsson',
      position: 'D',
      team: 'PIT',
      rank: 293,
      startPercentage: 71,
      rosPercentage: 83,
      status: 'healthy',
      value: 55.0,
      stats: {
        goals: 1,
        hockeyAssists: 13,
        hockeyPoints: 14,
        plusMinus: 7,
        pim: 6,
        ppp: 3,
        shp: 0,
        gwg: 0,
        sog: 40,
        hit: 0,
        blk: 24,
      },
    },
    // Util
    {
      id: 'zoey-matthews',
      name: 'Auston Matthews',
      position: 'C',
      team: 'TOR',
      rank: 70,
      startPercentage: 54,
      rosPercentage: 100,
      status: 'healthy',
      value: 75.0,
      stats: {
        goals: 9,
        hockeyAssists: 5,
        hockeyPoints: 14,
        plusMinus: 9,
        pim: 6,
        ppp: 2,
        shp: 0,
        gwg: 2,
        sog: 68,
        fw: 190,
        hit: 14,
        blk: 32,
      },
    },
    // Bench
    {
      id: 'zoey-weegar',
      name: 'MacKenzie Weegar',
      position: 'D',
      team: 'CGY',
      rank: 237,
      startPercentage: 76,
      rosPercentage: 84,
      status: 'healthy',
      value: 62.0,
      stats: {
        goals: 0,
        hockeyAssists: 4,
        hockeyPoints: 4,
        plusMinus: -20,
        pim: 31,
        ppp: 2,
        shp: 0,
        gwg: 0,
        sog: 51,
        hit: 62,
        blk: 49,
      },
    },
    {
      id: 'zoey-hyman',
      name: 'Zach Hyman',
      position: 'LW,RW',
      team: 'EDM',
      rank: 714,
      startPercentage: 13,
      rosPercentage: 81,
      status: 'healthy',
      value: 50.0,
      stats: {
        goals: 0,
        hockeyAssists: 2,
        hockeyPoints: 2,
        plusMinus: -4,
        pim: 4,
        ppp: 0,
        shp: 0,
        gwg: 0,
        sog: 12,
        hit: 22,
        blk: 1,
      },
    },
    {
      id: 'zoey-miller',
      name: 'J.T. Miller',
      position: 'C,RW',
      team: 'NYR',
      rank: 149,
      startPercentage: 45,
      rosPercentage: 91,
      status: 'healthy',
      value: 70.0,
      stats: {
        goals: 6,
        hockeyAssists: 7,
        hockeyPoints: 13,
        plusMinus: -6,
        pim: 8,
        ppp: 4,
        shp: 0,
        gwg: 1,
        sog: 51,
        fw: 206,
        hit: 56,
        blk: 8,
      },
    },
    // IR
    {
      id: 'zoey-duchene',
      name: 'Matt Duchene',
      position: 'C,RW',
      team: 'DAL',
      rank: 704,
      startPercentage: 9,
      rosPercentage: 53,
      status: 'IR',
      value: 40.0,
      stats: {
        goals: 1,
        hockeyAssists: 1,
        hockeyPoints: 2,
        plusMinus: 0,
        pim: 0,
        ppp: 1,
        shp: 0,
        gwg: 1,
        sog: 3,
        fw: 12,
        hit: 2,
        blk: 4,
      },
    },
    // Goaltenders
    {
      id: 'zoey-knight',
      name: 'Spencer Knight',
      position: 'G',
      team: 'CHI',
      rank: 31,
      startPercentage: 72,
      rosPercentage: 88,
      status: 'healthy',
      value: 75.0,
      stats: {
        wins: 7,
        losses: 5,
        goalsAgainst: 40,
        saves: 460,
        shotsAgainst: 500,
        svp: 0.920,
        shutouts: 1,
      },
    },
    {
      id: 'zoey-daccord',
      name: 'Joey Daccord',
      position: 'G',
      team: 'SEA',
      rank: 49,
      startPercentage: 46,
      rosPercentage: 76,
      status: 'healthy',
      value: 68.0,
      stats: {
        wins: 7,
        losses: 4,
        goalsAgainst: 38,
        saves: 366,
        shotsAgainst: 404,
        svp: 0.906,
        shutouts: 2,
      },
    },
    {
      id: 'zoey-vladar',
      name: 'Dan Vladar',
      position: 'G',
      team: 'PHI',
      rank: 56,
      startPercentage: 30,
      rosPercentage: 40,
      status: 'healthy',
      value: 65.0,
      stats: {
        wins: 9,
        losses: 4,
        goalsAgainst: 33,
        saves: 345,
        shotsAgainst: 378,
        svp: 0.913,
        shutouts: 0,
      },
    },
  ]

  return {
    id: 'zoey',
    name: 'Zoey',
    owner: 'Mark Z',
    record: '61-52-20',
    rank: 3,
    players,
  }
}

