import { Player } from '@/types'

/**
 * Sample player data for development and testing
 * In production, this would come from an API or database
 */
export const samplePlayers: Player[] = [
  // NFL Players
  {
    id: '1',
    name: 'Patrick Mahomes',
    position: 'QB',
    team: 'KC',
    value: 85.5,
    stats: { points: 320.5 },
    projectedStats: { points: 335.2 },
  },
  {
    id: '2',
    name: 'Josh Allen',
    position: 'QB',
    team: 'BUF',
    value: 82.3,
    stats: { points: 315.8 },
    projectedStats: { points: 328.5 },
  },
  {
    id: '3',
    name: 'Lamar Jackson',
    position: 'QB',
    team: 'BAL',
    value: 78.9,
    stats: { points: 298.3 },
    projectedStats: { points: 312.0 },
  },
  {
    id: '4',
    name: 'Christian McCaffrey',
    position: 'RB',
    team: 'SF',
    value: 92.1,
    stats: { points: 285.4 },
    projectedStats: { points: 298.7 },
  },
  {
    id: '5',
    name: 'Austin Ekeler',
    position: 'RB',
    team: 'LAC',
    value: 75.8,
    stats: { points: 245.6 },
    projectedStats: { points: 258.3 },
  },
  {
    id: '6',
    name: 'Derrick Henry',
    position: 'RB',
    team: 'TEN',
    value: 73.2,
    stats: { points: 238.9 },
    projectedStats: { points: 252.1 },
  },
  {
    id: '7',
    name: 'Tyreek Hill',
    position: 'WR',
    team: 'MIA',
    value: 88.7,
    stats: { points: 275.3 },
    projectedStats: { points: 289.5 },
  },
  {
    id: '8',
    name: 'Justin Jefferson',
    position: 'WR',
    team: 'MIN',
    value: 86.4,
    stats: { points: 268.7 },
    projectedStats: { points: 282.3 },
  },
  {
    id: '9',
    name: 'Davante Adams',
    position: 'WR',
    team: 'LV',
    value: 79.5,
    stats: { points: 245.2 },
    projectedStats: { points: 259.8 },
  },
  {
    id: '10',
    name: 'Travis Kelce',
    position: 'TE',
    team: 'KC',
    value: 81.3,
    stats: { points: 198.6 },
    projectedStats: { points: 212.4 },
  },
  
  // NBA Players
  {
    id: '11',
    name: 'Luka Dončić',
    position: 'PG',
    team: 'DAL',
    value: 95.2,
    stats: { points: 32.5, rebounds: 8.2, assists: 9.1, steals: 1.4, blocks: 0.5 },
    projectedStats: { points: 33.8, rebounds: 8.5, assists: 9.5, steals: 1.5, blocks: 0.5 },
  },
  {
    id: '12',
    name: 'Nikola Jokić',
    position: 'C',
    team: 'DEN',
    value: 93.8,
    stats: { points: 26.4, rebounds: 12.4, assists: 9.0, steals: 1.4, blocks: 0.9 },
    projectedStats: { points: 27.2, rebounds: 12.8, assists: 9.3, steals: 1.5, blocks: 1.0 },
  },
  {
    id: '13',
    name: 'Giannis Antetokounmpo',
    position: 'PF',
    team: 'MIL',
    value: 91.5,
    stats: { points: 30.4, rebounds: 11.5, assists: 6.5, steals: 1.2, blocks: 1.1 },
    projectedStats: { points: 31.2, rebounds: 11.8, assists: 6.8, steals: 1.3, blocks: 1.2 },
  },
  {
    id: '14',
    name: 'Stephen Curry',
    position: 'PG',
    team: 'GSW',
    value: 87.6,
    stats: { points: 26.4, rebounds: 4.5, assists: 5.1, steals: 0.8, blocks: 0.4 },
    projectedStats: { points: 27.1, rebounds: 4.6, assists: 5.3, steals: 0.9, blocks: 0.4 },
  },
  {
    id: '15',
    name: 'Jayson Tatum',
    position: 'SF',
    team: 'BOS',
    value: 85.3,
    stats: { points: 30.1, rebounds: 8.8, assists: 4.6, steals: 1.0, blocks: 0.5 },
    projectedStats: { points: 30.8, rebounds: 9.0, assists: 4.8, steals: 1.1, blocks: 0.6 },
  },
  {
    id: '16',
    name: 'Joel Embiid',
    position: 'C',
    team: 'PHI',
    value: 89.7,
    stats: { points: 33.1, rebounds: 10.2, assists: 4.2, steals: 1.0, blocks: 1.7 },
    projectedStats: { points: 33.8, rebounds: 10.5, assists: 4.4, steals: 1.1, blocks: 1.8 },
  },
  {
    id: '17',
    name: 'Kevin Durant',
    position: 'PF',
    team: 'PHX',
    value: 83.4,
    stats: { points: 29.1, rebounds: 6.7, assists: 5.0, steals: 0.8, blocks: 1.2 },
    projectedStats: { points: 29.6, rebounds: 6.9, assists: 5.1, steals: 0.9, blocks: 1.2 },
  },
  {
    id: '18',
    name: 'Shai Gilgeous-Alexander',
    position: 'SG',
    team: 'OKC',
    value: 88.9,
    stats: { points: 31.4, rebounds: 5.5, assists: 6.3, steals: 2.2, blocks: 0.8 },
    projectedStats: { points: 32.1, rebounds: 5.7, assists: 6.5, steals: 2.3, blocks: 0.9 },
  },
]

